project:
  type: website
  output-dir: docs

website:
  title: "Edan-Spector_Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: final.qmd
        text: Final Project
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

